name: flutter_highlight_korean_text
description: "Flutter_highlight_korean_text"
version: 1.0.0+1
homepage: https://github.com/TeddyYeung/flutter_highlight_korean_text
repository: https://github.com/TeddyYeung/flutter_highlight_korean_text

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: